all:
	cd lib
	make
	cd ..

	cd noyau
	make
	cd ..

	cd install
	make
	cd ..

	cd command
	make
	cd ..

copy: clean all
	copy noyau\systeme.sys b:

clean:
	cd lib
	make clean
	cd ..

	cd noyau
	make clean
	cd ..

	cd install
	make clean
	cd ..

	cd command
	make clean
	cd ..
