asm= lzasm /z/t
lnk= elink

all: commande.ce

commande.ce: commande.obj 
	$(lnk) commande.obj commande.ce

commande.obj: commande.asm
	$(asm) commande.asm

clean:
  del *.obj
  del *.ce
  del *.bak
  del *.lib
  del *.com
  del *.bin
  del *.sys
  del *.err