asm= lzasm /z/t
lnk= elink

all: detect.lib video.lib str0.lib bmp.lib

.asm.obj: 
      $(asm) $<

.obj.lib:
	$(lnk) $< $*.lib

clean:
  del *.obj
  del *.ce
  del *.bak
  del *.lib
  del *.com
  del *.bin
  del *.sys
  del *.err