asm= lzasm /z/t
lnk= elink

all: systeme.sys boot.bin

systeme.sys: video.obj disque.obj systeme.obj
	$(lnk) systeme.obj systeme.sys

systeme.obj: ..\lib\detect.lib ..\lib\video.lib video.sys disque.sys 
	$(asm) systeme.asm

disque.sys: 
	$(lnk) disque.obj disque.sys

video.sys: 
	$(lnk) video.obj video.sys

boot.bin: boot.obj
	$(lnk) boot.obj boot.bin /bs

video.obj:
	$(asm) video.asm 

disque.obj:
	$(asm) disque.asm

boot.obj:
	$(asm) boot.asm

clean:
  del *.obj
  del *.exe
  del *.bak
  del *.lib
  del *.com
  del *.bin
  del *.sys
  del *.err