asm= lzasm
lnk= elink

all: systeme.sys boot.bin

systeme.sys: video.obj systeme.obj
	$(lnk) systeme.obj systeme.sys

systeme.obj: ../lib/detect.lib ../lib/video.lib video.sys 
	$(asm) systeme.asm


video.sys: 
	$(lnk) video.obj video.sys

boot.bin: boot.obj
	$(lnk) boot.obj boot.bin /bs

detect.obj:
	$(asm) detect.asm

video.obj:
	$(asm) video.asm 

boot.obj:
	$(asm) boot.asm

clean:
  del *.obj
  del *.exe
  del *.bak
  del *.lib
  del *.com
  del *.bin
  del *.sys
  del *.err