lnk_boot = tlink /x
asm= tasm /t/m5/zi
lnk= tlink /x/t

all: ex-tasm.com ex-nasm.com

ex-tasm.com: ex-tasm.asm
	$(asm) ex-tasm
	$(lnk) ex-tasm
	ren ex-tasm.com ex-tasm.com

ex-nasm.com: ex-nasm.asm
	nasm ex-nasm.asm -o ex-nasm.com

clean:
  del *.obj
  del *.exe
  del *.com
  del *.sys
  del *.err
